<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add. filter: ' => 'Доп. фильтр: ',
    'Cancel Operation' => 'Отменить формирование отчета',
    'Cancel Report. Are you sure?' => 'Вы уверены, что хотите отменить формирование отчета?',
    'Clear' => 'Очистить',
    'Close' => 'Закрыть',
    'Delete All Reports. Are you sure?' => 'Вы уверены, что хотите удалить все отчеты?',
    'Delete Report. Are you sure?' => 'Вы уверены, что хотите удалить отчет?',
    'Download File' => 'Скачать файл отчета',
    'Empty' => 'Пусто',
    'Error' => 'Ошибка',
    'Error. File of report not found on server ({file})' => 'Ошибка. Файл отчета не найден на сервере ({file})',
    'Error. File remove error (({file}))' => 'Ошибка. Ошибка удаления файла (({file}))',
    'Error. Only Ajax Request Access' => 'Ошибка. Доступны только Ajax запросы',
    'Error. Report with id = "{id}" not found in database' => 'Ошибка. Отчет с id = "{id}" не найден в базе данных',
    'Error. id Variable Only Integer Access, Your Passed "{id}"' => 'Ошибка. В переданной переменной id могут быть только целые числа, Вы отправили "{id}"',
    'Remove File' => 'Удалить файл отчета',
    'Report Loader' => 'Загрузчик отчетов',
    'Report with id = "{value}" is formed' => 'Отчет с id = "{value}" уже формируется',
];
