<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add. filter: ' => 'Доп. фильтр: ',
    'In \'crudOptions\' array must be only this keys [\'create\', \'update\', \'delete\']. Passed \'{key}\'' => '',
    'In \'setPanelHeading\' array must be only this keys [\'icon\', \'title\']. Passed \'{key}\'' => '',
    'Report' => 'Отчет',
    'In \'customizeSettings\' array must be only this keys [\'filterShow\', \'exportShow\', \'customizeShow\']. Passed \'{key}\'' => '@@@@',
    'Additional Filter' => 'Дополнительный фильтр',
    'Apply' => 'Применить',
    'Cancel' => 'Отмена',
    'Close' => 'Закрыть',
    'Confirm' => 'Подтверждение',
    'Create' => 'Добавить',
    'Customize' => 'Настройки',
    'Customize Dialog' => 'Форма настройки таблицы',
    'Delete' => 'Удалить',
    'Drag to the left of the column that you want to see in the grid in a specific order' => '* Перенесите имена колонок, которые Вы хотите видеть в таблице, в левый список о определенном порядке',
    'Enter the number of records on the grid from 10 to 100' => 'Введите количество записей, отображаемых в таблице. От 10 до 100',
    'Export' => 'Экспорт',
    'Filter' => 'Фильтр',
    'Hidden Columns' => 'Скрытые колонки',
    'Information' => 'Информация',
    'No' => 'Нет',
    'OK' => 'ОК',
    'Reset' => 'Сброс настроек',
    'Reset Columns. Are you sure?' => 'Вы уверены, что хотите сбросить настройки?',
    'Reset Filter' => 'Сброс фильтра',
    'Reset Filter. Are you sure?' => 'Вы уверены, что хотите сбросить дополнительный фильтр?',
    'Reset Sort' => 'Сброс сортировки',
    'Reset Sort Grid. Are you sure?' => 'Вы уверены, что хотите сбросить сортировку на настройки по умолчанию?',
    'Rows Per Page' => 'Количество записей на страницу',
    'Rows per page must be from 10 to 100' => 'Количество записей должно быть указано от 10 до 100',
    'Save changes' => 'Сохранить',
    'Search' => 'Поиск',
    'Update' => 'Обновить',
    'Visible Columns' => 'Видимые колонки',
    'Visible columns cannot empty' => 'Список с видимыми колонками не может быть пустым',
    'Yes' => 'Да',
];
