<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Composer Update Date' => 'Последняя дата обновления пакетов проекта',
    'Current User' => 'Текущий пользователь',
    'Authentication Type' => 'Тип авторизации текущего пользователя',
    'Guest' => 'Гость',
    'LDAP' => 'Доменная',
    'Local' => 'Локальная',
    'Unknown' => 'Неизвестная',
    'PHP Version' => 'Версия PHP',
    'Yii Version' => 'Версия Yii',
    'Total {total}, Free {free} ({precent}%)' => 'Всего {total}, Свободно {free} ({precent}%)',
    'Disk Space' => 'Дисковое пространство на сервере',
    'Ldap Authentication is Active' => 'LDAP авторизация',
    'Use Only Ldap Authentication' => 'Использование авторизации только по LDAP',
    'Import Employee is Active' => 'Автоматический импорт сотрудников',
];
