<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Build ID' => '',
    'Dolzh ID' => '',
    'Employee History ID' => '',
    'Employee ID' => '',
    'Parttime ID' => '',
    'Person ID' => '',
    'Podraz ID' => '',
    'Profile ID' => '',
    'Build Name' => 'Здание',
    'Created At' => 'Время создания записи',
    'Created By' => 'Автор создавший запись',
    'Dolzh Name' => 'Должность',
    'Employee Begin' => 'Дата начала',
    'Employee History Begin' => 'Дата начала',
    'Parttime Begin' => 'Дата начала',
    'Parttime End' => 'Дата окончания',
    'Podraz Name' => 'Подразделение',
    'Profile Address' => 'Адрес',
    'Profile Dr' => 'Дата рождения',
    'Profile Inn' => 'ИНН',
    'Profile Pol' => 'Пол',
    'Profile Snils' => 'СНИЛС',
    'Updated At' => 'Время обновления записи',
    'Updated By' => 'Автор обновивший запись',
];
