<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Build ID' => '',
    'Employee History ID' => '',
    'Employee ID' => '',
    'Invalid UUID Parameters.' => '',
    'Person ID' => '',
    'URL parameter "employee" is missed.' => '',
    'URL parameter "person" is missed.' => '',
    'Unique Error By Values [PersonID: {person_id}, DolzhID: {dolzh_id}, PodrazID: {podraz_id}, {person_fullname}, From: {parttime_begin}, To: {parttime_end}]' => 'Совмешение у пользователя "{person_fullname}" с {parttime_begin} по {parttime_end} уже существует. (ИД Пользователя: {person_id}, ИД Должности: {dolzh_id}, ИД Подразделения: {podraz_id})',
    'Unique Error By Values [{person_id}, {person_fullname}, {employee_history_begin}]' => 'Специальность у пользователя {person_id} "{person_fullname}" на {employee_history_begin} уже существует.',
    'Dolzh ID' => 'Должность',
    'Dolzh Name' => 'Должность',
    'Employee Begin' => 'Дата начала',
    'Employee End' => 'Дата окончания',
    'Employee History Begin' => 'Дата начала',
    'Podraz ID' => 'Подразделение',
    'Podraz Name' => 'Подразделение',
    'Type' => 'Тип',
    'You need remove Parttimes' => 'Вам необходимо убрать совмещения',
];
