<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Person Auth Key' => '',
    'Person Code' => 'Код',
    'Person Email' => 'Электронная почта',
    'Person Fired' => 'Дата увольнения',
    'Person Fullname' => 'Фамилия Имя Отчество',
    'Person Hired' => 'Дата приема на работу',
    'Person ID' => 'ИД Пользователя',
    'Person Password Hash' => '',
    'Person Username' => 'Логин',
    'Person is saved. Add speciality.' => 'Пользователь сохранен. Добавьте специальность.',
    'Password very short. Need minimum 6 characters.' => 'Пароль должен содержать не менее 6 символов.',
    'Person Password' => 'Пароль',
    'Person Password Repeat' => 'Повторите ввод пароля',
    'Person not found.' => 'Пользователь не найден',
];
