<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Profile Internal Phone' => 'Внутренний телефон',
    'Profile Phone' => 'Телефон',
    'Dr Not Exist' => 'Отсутствует дата рождения',
    'INN Not Exist' => 'Отсутствует ИНН',
    'INN required 12 digits' => 'ИНН должен содержать 12 знаков',
    'Profile Address' => 'Адрес',
    'Profile Dr' => 'Дата рождения',
    'Profile ID' => 'ИД Пользователя',
    'Profile Inn' => 'ИНН',
    'Profile Pol' => 'Пол',
    'Profile Snils' => 'СНИЛС',
    'SNILS Not Exist' => 'Отсутствует СНИЛС',
];
